service: huh-bot
frameworkVersion: "2"
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
functions:
  slack:
    handler: src/app.handler
    events:
      - http:
          path: slack/huh
          method: post
plugins:
  - serverless-offline
